---
- name: Configuring node agents
  hosts: vpanainte_capstone_jenkins_node
  become: true
  tasks:
    - name: Installing required packages
      block:
        - name: Installing Java Development Kit for Jenkins agent
          ansible.builtin.apt:
            name: default-jdk
            state: present
            update_cache: true

        - name: Installing Docker GPG key
          ansible.builtin.get_url:
            url: https://download.docker.com/linux/ubuntu/gpg
            dest: /etc/apt/keyrings/docker.asc
            owner: root
            group: root
            mode: '0444'

        - name: Installing Terraform repository GPG key
          ansible.builtin.get_url:
            url: https://apt.releases.hashicorp.com/gpg
            dest: /etc/apt/keyrings/hashicorp.asc
            owner: root
            group: root
            mode: '0444'

        - name: Adding Docker Repository
          ansible.builtin.apt_repository:
            repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
            update_cache: true

        - name: Adding Terraform repository
          ansible.builtin.apt_repository:
            repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/hashicorp.asc] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
            update_cache: true

        - name: Installing Docker, Terraform, Ansible and their dependencies
          ansible.builtin.apt:
            name:
              - docker-ce
              - docker-ce-cli
              - terraform
              - ansible
              - unzip
              - python3-google-auth
              - acl
            state: present

        - name: Installing yamlfmt
          ansible.builtin.unarchive:
            src: https://github.com/google/yamlfmt/releases/download/v0.14.0/yamlfmt_0.14.0_Linux_x86_64.tar.gz
            dest: /usr/local/bin
            remote_src: true
            mode: '0755'

        - name: Installing Terraform Lint
          ansible.builtin.unarchive:
            src: https://github.com/terraform-linters/tflint/releases/download/v0.54.0/tflint_linux_amd64.zip
            dest: /usr/local/bin
            remote_src: true
            mode: '0755'

        - name: Installing Ansible Lint
          ansible.builtin.apt:
            name: ansible-lint
            state: present

    - name: Creating jenkins user
      ansible.builtin.user:
        name: jenkins
        shell: /bin/bash
        create_home: true
        home: /home/jenkins
        groups: docker
        append: true
        state: present

    - name: Adding master node public key to the list of authorized_keys on agent nodes
      ansible.posix.authorized_key:
        user: jenkins
        state: present
        key: "{{ ssh_key }}"

    - name: Configuring git username and email for jenkins user
      become: true
      become_user: jenkins
      block:
        - name: Configuring git username
          community.general.git_config:
            scope: global
            name: user.name
            value: jenkins

        - name: Configuring git email address
          community.general.git_config:
            scope: global
            name: user.email
            value: jenkins@jenkins.io
