---
- name: Configuring node agents
  hosts: vpanainte_capstone_jenkins_node
  become: true
  tasks:
    - name: Installing Java Runtime
      ansible.builtin.apt:
        name: default-jre
        state: present
        update_cache: true

    - name: Creating jenkins user
      ansible.builtin.user:
        name: jenkins
        shell: /bin/bash
        create_home: true
        home: /var/jenkins
        state: present

    - name: Adding master node public key to the list of authorized_keys on agent nodes
      ansible.builtin.authorized_key:
        user: jenkins
        state: present
        key: "{{ ssh_key }}"
